config/routes.rb
Rails.application.routes.draw do


  get 'intervention/index'
  # get 'geolocation/index'

  get 'intervention', to: 'intervention#index'
  get 'geolocation',  to: 'geolocation#index'

  mount RailsAdmin::Engine => '/backoffice', as: 'rails_admin'
  


  resources :leads
  resources :quotes , only: [:user_quotes, :new, :create]

  root to: 'static_pages#index'
  get 'static_pages/residential'
  get 'static_pages/corporate'
  get 'static_pages/streamer'

  devise_for :users,
  :controllers => { registrations: 'registrations'},
  :path_prefix => '',
  path: 'u',
  path_names: {
    sign_in: 'sign_in',
    sign_out: 'sign_out',
    password: 's',
    confirmation: 'v'
  }

  get 'my_quotes' => 'quotes#user_quotes', as: :my_quotes
  get 'my_leads' => 'leads#user_leads', as: :my_leads
  get 'my_interventions' => 'intervention#my_intervention'
  match '/watson' => 'watson#speak', via: :get

  # collection routes 
  resources :intervention do
  get :get_building, on: :collection
  get :get_battery, on: :collection
  get :get_column, on: :collection
  get :get_elevator, on: :collection
  end 
  

end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :user, optional: true
  # after_create :new_quote_ticket
  # after_save :save_to_dwh

def save_to_dwh
 FactQuote.create!({quote_id: self.id})
end


  # When a user enters data in the submission page, this information is sent to the zendesk application depending on the type of building
   
  def new_quote_ticket

    if self.building_type == "Residential" 
      comment = { :value => "#{self.user.first_name} #{self.user.last_name} sent us a quote request and can be reached at #{self.user.email}. \nThis quotes was created in #{self.created_at}. The type of building is #{building_type} and the gamme choosen was #{self.product_line}. \n Here are the parameters : \n Number of apartments : #{self.apartments} \n Number of floor : #{self.floors} \n Number of Basement : #{self.basements} \n Total Elevators Required : #{elevator_number}    Total cost is : #{self.total_price} $" }
    
    elsif self.building_type == "Commercial"
      comment = { :value => "#{self.user.first_name} #{self.user.last_name} sent us a quote request and can be reached at #{self.user.email}. \nThis quotes was created in #{self.created_at}. The type of building is #{building_type} and the gamme choosen was #{self.product_line}. \n Here are the parameters : \n Number of floor : #{self.floors}\n Number of Basement : #{self.basements} \n Number of Buisnesses : #{self.businesses} \n Number of Elevator Shafts : #{self.elevator_shafts} \n Number of parking spaces : #{self.parking_spaces} \n Total Elevators Required : #{elevator_number}    Total cost is : #{self.total_price} $" }
    
    elsif self.building_type == "Corporate"
      comment = { :value => "#{self.user.first_name} #{self.user.last_name} sent us a quote request and can be reached at #{self.user.email}. \nThis quotes was created in #{self.created_at}. The type of building is #{building_type} and the gamme choosen was #{self.product_line}. \n Here are the parameters : \n Number of floor : #{self.floors}\n Number of Basement : #{self.basements} \n Number of Buisnesses : #{self.businesses} \n Number of parking spaces : #{self.parking_spaces} \n Number of occupants : #{self.occupants} \n Total Elevators Required : #{elevator_number}    Total cost is : #{self.total_price} $" }
    
    elsif self.building_type == "Hybrid"
      comment = { :value => "#{self.user.first_name} #{self.user.last_name} sent us a quote request and can be reached at #{self.user.email}. \nThis quotes was created in #{self.created_at}. The type of building is #{building_type} and the gamme choosen was #{self.product_line}. \n Here are the parameters : \n Number of floor : #{self.floors}\n Number of Basement : #{self.basements} \n Number of Buisnesses : #{self.businesses} \n Number of parking spaces : #{self.parking_spaces} \n Number of occupants : #{self.occupants} \n Opening hours : #{self.opening_hours} \n Total Elevators Required : #{elevator_number}    Total cost is : #{self.total_price} $" }

    end

    # This part is the configuration of zendesk api 
   

    client = ZendeskAPI::Client.new do |config|
      config.url = 'https://rocketelevators8100.zendesk.com/api/v2'
      config.username = 'saadeddine.feki@gmail.com'
      config.token = ENV["zendesk_api"]
      end 

    # This part create a ticket with a subject and the body, the body come from the comment at the top of the page depending on the type of building


    ZendeskAPI::Ticket.create!(client,
    :subject => "Quote Request", 
    :comment => comment,
    
    # This is the priority for viewing tickets, if urgent, tickets will appear at the top of the list

    :priority => "normal",
    :type => "Question"
    )
  end


end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :authenticate_user!

  # GET /quotes
  # GET /quotes.json
  def user_quotes
    @quotes = Quote.where(:user_id => current_user.id)
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)
    @quote.user_id = current_user.id
    if verify_recaptcha(model: @lead)
      @quote.save
      respond_to do |format|
          if @quote.save 
            format.html { redirect_to my_quotes_path, notice: 'Quote was successfully created !' }
          else         
            format.html { render :new }
          end
        end
    else
      
      render :new
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:apartments, :floors, :basements, :businesses, :elevator_shafts, :parking_spaces, :occupants, :opening_hours, :product_line, :install_fee, :total_price, :unit_price, :elevator_number, :building_type, :user_id)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_commercial.html.erb
         <%= simple_form_for(@quote) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="container">
    <div class="form-inputs row text-center">
      <%= f.input :floors, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true' %>
      <%= f.input :basements, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true' %>
      <%= f.input :businesses, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true' %>
      <%= f.input :elevator_shafts, input_html: {id: "cages"}, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true' %>
      <%= f.input :parking_spaces, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true' %>
    </div>
    <div class="form-inputs row">
      <%= f.input :product_line, as: :radio_buttons, collection: [['Standard'], ['Premium'], ['Excelium']], label_method: :first, value_method: :first, required: 'true'  %>
    </div>
     <div class="form-inputs row justify-content-center">
 
    <%= recaptcha_tags required: 'true' %>
    </div>
    <%= f.hidden_field :total_price, class: "total_price" %>
    <%= f.hidden_field :install_fee, class: "install_fee" %>
    <%= f.hidden_field :elevator_number, class: "elevator_number" %>
    <%= f.hidden_field :building_type, class: "building_type" %>
    <div class="form-actions text-center">
      <%= f.button :submit, class: "btn btn-lg btn-red" %>
      <input type="reset" class="btn btn-lg btn-default">
      <hr />
      <%= render 'quoteinfo' %>
    </div>
  </div>
<% end %>

app/views/quotes/_corporate.html.erb
         <%= simple_form_for(@quote) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="container">
    <div class="form-inputs row text-center">
      <%= f.input :floors, input_html: {id: "floors"}, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true' %>
      <%= f.input :basements, input_html: {id: "basements"}, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true' %>
      <%= f.input :businesses, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true' %>
      <%= f.input :parking_spaces, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true' %>
      <%= f.input :occupants, input_html: {id: "occupants"}, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true' %>
    </div>
    <div class="form-inputs row">
      <%= f.input :product_line, as: :radio_buttons, collection: [['Standard'], ['Premium'], ['Excelium']], label_method: :first, value_method: :first, required: 'true'  %>
    </div>
     <div class="form-inputs row justify-content-center">
 
    <%= recaptcha_tags %>
    </div>
    <%= f.hidden_field :total_price, class: "total_price" %>
    <%= f.hidden_field :install_fee, class: "install_fee" %>
    <%= f.hidden_field :elevator_number, class: "elevator_number" %>
    <%= f.hidden_field :building_type, class: "building_type" %>
    <div class="form-actions text-center">
      <%= f.button :submit, class: "btn btn-lg btn-red" %>
      <input type="reset" class="btn btn-lg btn-default">
      <hr />
      <%= render 'quoteinfo' %>
    </div>
  </div>
<% end %>

app/views/quotes/_hybrid.html.erb
<%= simple_form_for(@quote) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="container">
    <div class="form-inputs row text-center">
      <%= f.input :floors, input_html: {id: "floors"}, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true' %>
      <%= f.input :basements, input_html: {id: "basements"}, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true' %>
      <%= f.input :businesses, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true' %>
      <%= f.input :parking_spaces, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true' %>
      <%= f.input :occupants, input_html: {id: "occupants"}, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true' %>
      <%= f.input :opening_hours, collection: 1..24 , :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true' %>
    </div>
    <div class="form-inputs row">
      <%= f.input :product_line, as: :radio_buttons, collection: [['Standard'], ['Premium'], ['Excelium']], label_method: :first, value_method: :first, required: 'true'  %>
    </div>
     <div class="form-inputs row justify-content-center">
 
    <%= recaptcha_tags %>
    </div>
    <%= f.hidden_field :total_price, class: "total_price" %>
    <%= f.hidden_field :install_fee, class: "install_fee" %>
    <%= f.hidden_field :elevator_number, class: "elevator_number" %>
    <%= f.hidden_field :building_type, class: "building_type" %>
    <div class="form-actions text-center">
      <%= f.button :submit, class: "btn btn-lg btn-red" %>
      <input type="reset" class="btn btn-lg btn-default">
      <hr />
      <%= render 'quoteinfo' %>
    </div>
  </div>
<% end %>

app/views/quotes/_quoteinfo.html.erb
<div class="row">
  <div class="col-lg-3">
    <label class="text-center">Total Elevators Required</label>
    <input type="text" disabled="true" placeholder="..." class="form-control" id="total_elev">
  </div>
  <div class="col-lg-3">
    <label class="text-center">Elevator Cost</label>
    <input type="text" disabled="true" placeholder="..." class="form-control" id="cost">
  </div>
  <div class="col-lg-3">
    <label class="text-center">Installation Fee</label>
    <input type="text" disabled="true" placeholder="..." class="form-control" id="fees">
  </div>
  <div class="col-lg-3">
    <label class="text-center">Total Cost</label>
    <input type="text" disabled="true" placeholder="..." class="form-control" id="total_cost">
  </div>
</div>

app/views/quotes/_residential.html.erb
  <%= simple_form_for(@quote) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="container">
    <div class="form-inputs row text-center">
      <%= f.input :apartments, input_html: { id: "apartments" }, required: 'true' %>
      <%= f.input :floors, input_html: { id: "floors" }, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true'  %>
      <%= f.input :basements, input_html: { id: "basements" }, :onkeydown => 'return event.keyCode !== 69 && event.keyCode !== 189', required: 'true'  %>
    </div>
    <div class="form-inputs row">
      <%= f.input :product_line, as: :radio_buttons, collection: [['Standard'], ['Premium'], ['Excelium']], label_method: :first, value_method: :first, required: 'true'  %>
   </div>
 <div class="form-inputs row justify-content-center">
 
    <%= recaptcha_tags %>
    </div>
    <%= f.hidden_field :total_price, class: "total_price" %>
    <%= f.hidden_field :install_fee, class: "install_fee" %>
    <%= f.hidden_field :elevator_number, class: "elevator_number" %>
    <%= f.hidden_field :building_type, class: "building_type" %>
    <div class="form-actions text-center">
     
      <%= f.button :submit, class: "btn btn-lg btn-red" %>
      <input type="reset" class="btn btn-lg btn-default">
      <hr />
      <%= render 'quoteinfo' %>
    </div>
  </div>
<% end %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Apartments</th>
      <th>Floors</th>
      <th>Basements</th>
      <th>Businesses</th>
      <th>Elevator shafts</th>
      <th>Parking spaces</th>
      <th>Occupants</th>
      <th>Opening hours</th>
      <th>Product line</th>
      <th>Install fee</th>
      <th>Total price</th>
      <th>Unit price</th>
      <th>Elevator number</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.apartments %></td>
        <td><%= quote.floors %></td>
        <td><%= quote.basements %></td>
        <td><%= quote.businesses %></td>
        <td><%= quote.elevator_shafts %></td>
        <td><%= quote.parking_spaces %></td>
        <td><%= quote.occupants %></td>
        <td><%= quote.opening_hours %></td>
        <td><%= quote.product_line %></td>
        <td><%= quote.install_fee %></td>
        <td><%= quote.total_price %></td>
        <td><%= quote.unit_price %></td>
        <td><%= quote.elevator_number %></td>
        <td><%= quote.user_id %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<section class="parallax parallax-1" id="parallax-quote-1" >
  <div class="overlay dark-5">
  </div>
  <div class="container">
    <div class="text-center">
      <h2 class="fs-90 fw-300">GET A QUOTE</h2>
      <a class="btn btn-lg btn-default btn-lg" href="/">HOME <i class="fa fa-angle-right"></i></a>
      &nbsp; OR &nbsp;
      <%= link_to root_path(anchor: "contact"), 'data-turbolinks': false do %>
        <span class="btn btn-lg btn-red">CONTACT US <i class="fa fa-angle-right"></i></span>
      <% end %>
    </div>
  </div>
</section>
<section style="padding: 0;">
  <div class="heading-title heading-dotted text-center mt-35">
    <h3 class="fs-50">Select the type <span> of building</span></h3>
  </div>
  <div class="accordion md-accordion accordion-4" id="accordionEx2" role="tablist" aria-multiselectable="true">
    <div class="card mb-0" id="res-card">
      <div class="card-header z-depth-1 teal lighten-4" role="tab" id="res">
        <a data-toggle="collapse" data-parent="#accordionEx2" href="#collapse10" aria-expanded="true" aria-controls="collapse10" class="d-flex justify-content-center">
          <div button type="button"
                class="btn btn-lg btn-outline-danger text-center bold"
                style="width: 50%;">
            Residential
          </div>
        </a>
      </div>
      <div id="collapse10" class="collapse" role="tabpanel" aria-labelledby="res"
            data-parent="#accordionEx2">
        <div class="rgba-teal-strong white-text">
          <%= render 'residential' %>
        </div>
      </div>
    </div>
    <div class="card mb-0" id="com-card">
      <div class="card-header z-depth-1 teal lighten-3" role="tab" id="com">
        <a data-toggle="collapse" data-parent="#accordionEx2" href="#collapse11" aria-expanded="false" aria-controls="collapse11" class="d-flex justify-content-center">
          <div button type="button"
                  class="btn btn-lg btn-outline-info text-center bold" style="width: 50%;">
            Commercial
          </div>
        </a>
      </div>
      <div id="collapse11" class="collapse" role="tabpanel" aria-labelledby="com"
              data-parent="#accordionEx2">
        <div class="rgba-teal-strong white-text">
          <%= render 'commercial' %>
        </div>
      </div>
    </div>
    <div class="card mb-0" id="cor-card">
      <div class="card-header z-depth-1 teal lighten-2" role="tab" id="cor">
        <a data-toggle="collapse" data-parent="#accordionEx2" href="#collapse12"
                aria-expanded="false" aria-controls="collapse12" class="d-flex justify-content-center">
          <div button type="button"
                  class="btn btn-lg btn-outline-danger text-center font-weight-bold"
                  style="width: 50%;">
            Corporate
          </div>
        </a>
      </div>
      <div id="collapse12" class="collapse" role="tabpanel" aria-labelledby="cor"
              data-parent="#accordionEx2">
        <div class="rgba-teal-strong white-text">
          <%= render 'corporate' %>
        </div>
      </div>
    </div>
    <div class="card mb-0" id="hyb-card">
      <div class="card-header z-depth-1 teal lighten-1" role="tab" id="hyb">
        <a data-toggle="collapse" data-parent="#accordionEx2" href="#collapse13"
                aria-expanded="true" aria-controls="collapse13" class="d-flex justify-content-center">
          <div button type="button"
                  class="btn btn-lg btn-outline-info text-center font-weight-bold"
                  style="width: 50%;">
            Hybrid
          </div>
        </a>
      </div>
      <div id="collapse13" class="collapse" role="tabpanel" aria-labelledby="hyb"
              data-parent="#accordionEx2">
        <div class="rgba-teal-strong white-text">
          <%= render 'hybrid' %>
        </div>
      </div>
    </div>
  </section>
  <section class="info-bar info-bar-color">
    <div class="container">
      <div class="row">
        <div class="col-sm-4 text-center">
          <h3>BUISNESS WORLDWIDE</h3>
          <p>We do business all over the world</p>
        </div>
        <div class="col-sm-4 text-center">
          <h3>SATISFACTION GUARANTEE</h3>
          <p>Peace of mind with us</p>
        </div>
        <div class="col-sm-4 text-center">
          <h3>ONLINE SUPPORT 24/7</h3>
          <p>We're here for you</p>
        </div>
      </div>
    </div>
  </section>
  <script>
    plugin_path = '../assets/';
  </script>
  <a href="#" id="toTop">
    <span class="arrow-top">▲</span>
  </a>

app/views/quotes/user_quotes.html.erb
<section>
  <div class="container">
    <div class="text-center">
      <h1 class="fw-300 text-blue">My Quotes</h1>
    </div>
    <div class="container">
      <p id="notice"><%= notice %></p>
      <table class="table table-striped">
        <thead>
          <tr>
            <%# <th>Apartments</th>
            <th>Floors</th>
            <th>Basements</th>
            <th>Businesses</th>
            <th>Elevator shafts</th>
            <th>Parking spaces</th>
            <th>Occupants</th>%>
            <th scope="col">Building Type</th>
            <th scope="col">Required Elevators</th>
            <th scope="col">Product Line</th>
            <th scope="col">Installation Fees</th>
            <th scope="col">Total Cost</th>
          </tr>
        </thead>
        <tbody>
          <% @quotes.each do |quote| %>
            <tr>
              <td><%= quote.building_type %></td>
              <td><%= quote.elevator_number %></td>
              <td><%= quote.product_line %></td>
              <td><%= number_to_currency(quote.install_fee, :unit => "$") %></td>
              <td><%= number_to_currency(quote.total_price, :unit => "$") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
      <div class="text-center">
        <%= button_to "New Quote", { :action => "new" }, :method => :get, :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
  <a href="/#contact">
    <span class="btn btn-xlg btn-red fs-20 fullwidth m-0 rad-0 p-40">
      <span class="font-lato fs-30">
        Ready to move forward? 
        <strong>Contact Us &raquo;</strong>
      </span>
    </span>
  </a>
</section>